### PR TITLE
Changed form key in POST to force multipart/form-data request

### PR DESCRIPTION
**Pull request by simonwillcock**
The Slack API requires that [files uploaded must use multipart/form-data](https://api.slack.com/methods/files.upload) otherwise you are returned the `invalid_array_arg` error. 

Changing the request form key to formData will make the request library use  multipart/form-data as seen in [the example in the readme](https://github.com/request/request#multipartform-data-multipart-form-uploads)

### CODE REVIEW

**Comment by nobuta** [comment]
:+1:

**Comment by kevinburkeshyp** [comment]
would be nice to have a test for this :(

**Comment by kevinburkeshyp** [comment]
merged as a4e98fc0e9be04741589bae6128a9529f4d039d1, thanks!

**Comment by simonwillcock** [comment]
Ah, yeah sorry I didn't think about a test! I'm still learning the ins and outs of unit testing. But thanks for the merge :)

**Pull request closed without merging**
